"""document templates, sequences, issued documents, branding

Revision ID: 300c3632c3b0
Revises: c9d2fddf27c5
Create Date: 2026-08-11 06:18:53.832644
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.rls import apply_rls, grant_app_role, verify_rls

revision: str = '300c3632c3b0'
down_revision: str | None = 'c9d2fddf27c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_profiles',
    # `config_status` already exists: `terminology_sets` created it. Reusing the
    # type rather than redeclaring it, because every versioned configuration
    # document in the product draws, publishes and archives the same way.
    sa.Column('status', postgresql.ENUM('draft', 'published', 'archived', name='config_status', create_type=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('crest_url', sa.String(length=500), nullable=True),
    sa.Column('signature_image_url', sa.String(length=500), nullable=True),
    sa.Column('watermark_url', sa.String(length=500), nullable=True),
    sa.Column('primary_colour', sa.String(length=9), nullable=True),
    sa.Column('accent_colour', sa.String(length=9), nullable=True),
    sa.Column('ink_colour', sa.String(length=9), nullable=True),
    sa.Column('heading_font', sa.String(length=120), nullable=True),
    sa.Column('body_font', sa.String(length=120), nullable=True),
    sa.Column('letterhead_note', sa.Text(), nullable=True),
    sa.Column('footer_note', sa.Text(), nullable=True),
    sa.Column('verification_url_template', sa.String(length=500), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'parent_version_id'], ['branding_profiles.tenant_id', 'branding_profiles.id'], name='fk_branding_profiles_parent_version_id_tenant', ondelete='SET NULL (parent_version_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_branding_profiles_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branding_profiles')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_branding_profiles_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_branding_tenant_version')
    )
    op.create_index(op.f('ix_branding_profiles_tenant_id'), 'branding_profiles', ['tenant_id'], unique=False)
    op.create_table('document_sequences',
    sa.Column('scope_key', sa.String(length=120), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_sequences_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_document_sequences_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'scope_key', name='uq_document_sequences_tenant_scope')
    )
    op.create_index(op.f('ix_document_sequences_tenant_id'), 'document_sequences', ['tenant_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('purpose_label', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='document_template_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numbering', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('freeze_branding', sa.Boolean(), nullable=False),
    sa.Column('published_results_only', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'parent_version_id'], ['document_templates.tenant_id', 'document_templates.id'], name='fk_document_templates_parent_version_id_tenant', ondelete='SET NULL (parent_version_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_templates_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates')),
    sa.UniqueConstraint('tenant_id', 'code', 'version', name='uq_document_templates_code_version'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_document_templates_tenant_id_id')
    )
    op.create_index(op.f('ix_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False)
    op.create_index('ix_document_templates_tenant_status', 'document_templates', ['tenant_id', 'status'], unique=False)
    op.create_table('documents',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_code', sa.String(length=60), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('purpose_label', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('academic_period_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'superseded', 'void', name='document_status'), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('verification_code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_documents_positive_version')),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_period_id'], ['academic_periods.tenant_id', 'academic_periods.id'], name='fk_documents_academic_period_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_year_id'], ['academic_years.tenant_id', 'academic_years.id'], name='fk_documents_academic_year_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_documents_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'supersedes_id'], ['documents.tenant_id', 'documents.id'], name='fk_documents_supersedes_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'template_id'], ['document_templates.tenant_id', 'document_templates.id'], name='fk_documents_template_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_documents_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_documents_tenant_number'),
    sa.UniqueConstraint('tenant_id', 'verification_code', name='uq_documents_tenant_verification')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index('ix_documents_tenant_subject', 'documents', ['tenant_id', 'student_relationship_id'], unique=False)
    op.create_index('ix_documents_tenant_template', 'documents', ['tenant_id', 'template_id'], unique=False)
    op.add_column('published_results', sa.Column('credits', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('published_results', sa.Column('credit_unit_label', sa.String(length=60), nullable=True))
    op.add_column('published_results', sa.Column('weight', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###
    _protect()


# `config_status` is deliberately absent: this revision did not create it, and
# dropping it here would take `terminology_sets` with it.
ENUM_TYPES = ("document_template_status", "document_status")


def _protect() -> None:
    """Apply row-level security, re-issue the grants, and verify.

    `documents` is not append-only — a document is voided and superseded in
    place — but it is undeletable, and that is enforced by the grant rather than
    by the code that happens to be calling.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('published_results', 'weight')
    op.drop_column('published_results', 'credit_unit_label')
    op.drop_column('published_results', 'credits')
    op.drop_index('ix_documents_tenant_template', table_name='documents')
    op.drop_index('ix_documents_tenant_subject', table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_document_templates_tenant_status', table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_tenant_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_document_sequences_tenant_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    op.drop_index(op.f('ix_branding_profiles_tenant_id'), table_name='branding_profiles')
    op.drop_table('branding_profiles')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
