"""Attendance: codes, registers, marks, and the amendment ledger.

An attendance record is evidence. It is quoted in safeguarding referrals, in
exclusion appeals, in funding audits and in court, so the shape here is closer
to the enrolment ledger than to a checkbox grid.

`attendance_amendments` joins the append-only tables: a mark may be corrected —
the child who arrived at half past nine was absent at nine, and the register was
right both times — but the correction is recorded with a reason, and the
application role holds no UPDATE or DELETE on the ledger.

Revision ID: 3178931baec9
Revises: 9c48a2f93f57
Create Date: 2026-08-11 03:26:58.273245
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = '3178931baec9'
down_revision: str | None = '9c48a2f93f57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('present', 'absent', 'late', 'excused', 'other', name='attendance_mark_category'), nullable=False),
    sa.Column('counts_as_present', sa.Boolean(), nullable=False),
    sa.Column('requires_reason', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('colour', sa.String(length=9), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_codes_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_codes')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_attendance_codes_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_attendance_codes_tenant_id_id')
    )
    op.create_index(op.f('ix_attendance_codes_tenant_id'), 'attendance_codes', ['tenant_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('class_group_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('academic_period_id', sa.UUID(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('open', 'submitted', 'amended', name='attendance_session_status'), nullable=False),
    sa.Column('taken_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('class_group_id IS NOT NULL OR course_id IS NOT NULL', name=op.f('ck_attendance_sessions_names_a_group')),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_period_id'], ['academic_periods.tenant_id', 'academic_periods.id'], name='fk_attendance_sessions_academic_period_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'class_group_id'], ['class_groups.tenant_id', 'class_groups.id'], name='fk_attendance_sessions_class_group_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'course_id'], ['courses.tenant_id', 'courses.id'], name='fk_attendance_sessions_course_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_sessions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sessions')),
    sa.UniqueConstraint('tenant_id', 'class_group_id', 'course_id', 'occurred_on', 'slot', name='uq_attendance_sessions_moment'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_attendance_sessions_tenant_id_id')
    )
    op.create_index('ix_attendance_sessions_tenant_date', 'attendance_sessions', ['tenant_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_tenant_id'), 'attendance_sessions', ['tenant_id'], unique=False)
    op.create_table('attendance_marks',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('code_id', sa.UUID(), nullable=False),
    sa.Column('minutes_late', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'code_id'], ['attendance_codes.tenant_id', 'attendance_codes.id'], name='fk_attendance_marks_code_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'session_id'], ['attendance_sessions.tenant_id', 'attendance_sessions.id'], name='fk_attendance_marks_session_id_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_attendance_marks_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_marks_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_marks')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_attendance_marks_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'session_id', 'student_relationship_id', name='uq_attendance_marks_session_student')
    )
    op.create_index(op.f('ix_attendance_marks_tenant_id'), 'attendance_marks', ['tenant_id'], unique=False)
    op.create_index('ix_attendance_marks_tenant_student', 'attendance_marks', ['tenant_id', 'student_relationship_id'], unique=False)
    op.create_table('attendance_amendments',
    sa.Column('mark_id', sa.UUID(), nullable=False),
    sa.Column('previous_code_id', sa.UUID(), nullable=True),
    sa.Column('new_code_id', sa.UUID(), nullable=True),
    sa.Column('previous_reason', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_membership_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'mark_id'], ['attendance_marks.tenant_id', 'attendance_marks.id'], name='fk_attendance_amendments_mark_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_amendments_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_amendments')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_attendance_amendments_tenant_id_id')
    )
    op.create_index(op.f('ix_attendance_amendments_tenant_id'), 'attendance_amendments', ['tenant_id'], unique=False)
    op.create_index('ix_attendance_amendments_tenant_mark', 'attendance_amendments', ['tenant_id', 'mark_id'], unique=False)
    # ### end Alembic commands ###
    _protect()


ENUM_TYPES = ("attendance_mark_category", "attendance_session_status")


def _protect() -> None:
    """Apply row-level security, re-issue the grants, and verify.

    Re-issuing matters here for a specific reason: without it
    `attendance_amendments` would be created carrying the UPDATE and DELETE this
    revision exists to withhold.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_amendments_tenant_mark', table_name='attendance_amendments')
    op.drop_index(op.f('ix_attendance_amendments_tenant_id'), table_name='attendance_amendments')
    op.drop_table('attendance_amendments')
    op.drop_index('ix_attendance_marks_tenant_student', table_name='attendance_marks')
    op.drop_index(op.f('ix_attendance_marks_tenant_id'), table_name='attendance_marks')
    op.drop_table('attendance_marks')
    op.drop_index(op.f('ix_attendance_sessions_tenant_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_tenant_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_attendance_codes_tenant_id'), table_name='attendance_codes')
    op.drop_table('attendance_codes')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
