"""research supervision, milestones and meetings

Revision ID: 329c59898206
Revises: d0250724ba40
Create Date: 2026-08-11 10:48:15.584636
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.rls import apply_rls, grant_app_role, verify_rls

revision: str = '329c59898206'
down_revision: str | None = 'd0250724ba40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `drop_table` leaves the enum type behind, and the next `upgrade` then fails
# on a type that already exists. Named here so the downgrade is genuinely a
# downgrade rather than a state nothing can migrate out of.
ENUM_TYPES = ("milestone_state",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervision_meetings',
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('staff_relationship_id', sa.UUID(), nullable=True),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('next_meeting_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'staff_relationship_id'], ['staff_relationships.tenant_id', 'staff_relationships.id'], name='fk_supervision_meetings_staff_relationship_id_tenant', ondelete='SET NULL (staff_relationship_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_supervision_meetings_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_supervision_meetings_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervision_meetings')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_supervision_meetings_tenant_id_id')
    )
    op.create_index(op.f('ix_supervision_meetings_tenant_id'), 'supervision_meetings', ['tenant_id'], unique=False)
    op.create_index('ix_supervision_meetings_tenant_researcher', 'supervision_meetings', ['tenant_id', 'student_relationship_id', 'held_on'], unique=False)
    op.create_table('supervisions',
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('staff_relationship_id', sa.UUID(), nullable=False),
    sa.Column('supervision_role_id', sa.UUID(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('ended_reason', sa.String(length=200), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('ended_on IS NULL OR ended_on >= started_on', name=op.f('ck_supervisions_ends_after_start')),
    sa.ForeignKeyConstraint(['tenant_id', 'staff_relationship_id'], ['staff_relationships.tenant_id', 'staff_relationships.id'], name='fk_supervisions_staff_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_supervisions_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'supervision_role_id'], ['supervision_roles.tenant_id', 'supervision_roles.id'], name='fk_supervisions_supervision_role_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_supervisions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervisions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_supervisions_tenant_id_id')
    )
    op.create_index(op.f('ix_supervisions_tenant_id'), 'supervisions', ['tenant_id'], unique=False)
    op.create_index('ix_supervisions_tenant_researcher', 'supervisions', ['tenant_id', 'student_relationship_id'], unique=False)
    op.create_index('ix_supervisions_tenant_supervisor', 'supervisions', ['tenant_id', 'staff_relationship_id', 'ended_on'], unique=False)
    op.create_index('uq_supervisions_open', 'supervisions', ['tenant_id', 'student_relationship_id', 'staff_relationship_id', 'supervision_role_id'], unique=True, postgresql_where=sa.text('ended_on IS NULL'))
    op.create_table('research_milestones',
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('milestone_definition_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('expected', 'scheduled', 'submitted', 'passed', 'referred', 'failed', 'waived', name='milestone_state'), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('submitted_on', sa.Date(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('outcome_label', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(state IN ('passed', 'referred', 'failed', 'waived')) = (decided_on IS NOT NULL)", name=op.f('ck_research_milestones_decision_dated')),
    sa.CheckConstraint('submitted_on IS NULL OR decided_on IS NULL OR decided_on >= submitted_on', name=op.f('ck_research_milestones_decision_after_submission')),
    sa.ForeignKeyConstraint(['tenant_id', 'milestone_definition_id'], ['milestone_definitions.tenant_id', 'milestone_definitions.id'], name='fk_research_milestones_milestone_definition_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_research_milestones_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_research_milestones_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_milestones')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_research_milestones_tenant_id_id')
    )
    op.create_index('ix_research_milestones_tenant_due', 'research_milestones', ['tenant_id', 'due_on'], unique=False)
    op.create_index(op.f('ix_research_milestones_tenant_id'), 'research_milestones', ['tenant_id'], unique=False)
    op.create_index('uq_research_milestones_researcher_definition', 'research_milestones', ['tenant_id', 'student_relationship_id', 'milestone_definition_id'], unique=True)
    # ### end Alembic commands ###
    _protect()


def _protect() -> None:
    """Three new tenant-owned tables get their policy before anything is written.

    Not an afterthought and not a follow-up revision: a table that exists for
    one deploy without row-level security is a table whose isolation depends on
    every query in that deploy having remembered its `WHERE`.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_research_milestones_researcher_definition', table_name='research_milestones')
    op.drop_index(op.f('ix_research_milestones_tenant_id'), table_name='research_milestones')
    op.drop_index('ix_research_milestones_tenant_due', table_name='research_milestones')
    op.drop_table('research_milestones')
    op.drop_index('uq_supervisions_open', table_name='supervisions', postgresql_where=sa.text('ended_on IS NULL'))
    op.drop_index('ix_supervisions_tenant_supervisor', table_name='supervisions')
    op.drop_index('ix_supervisions_tenant_researcher', table_name='supervisions')
    op.drop_index(op.f('ix_supervisions_tenant_id'), table_name='supervisions')
    op.drop_table('supervisions')
    op.drop_index('ix_supervision_meetings_tenant_researcher', table_name='supervision_meetings')
    op.drop_index(op.f('ix_supervision_meetings_tenant_id'), table_name='supervision_meetings')
    op.drop_table('supervision_meetings')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
