"""academic structure and terminology

Revision ID: 663c2b59c63f
Revises: e7543f431749
Create Date: 2026-08-10 20:14:03.060252
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = '663c2b59c63f'
down_revision: str | None = 'e7543f431749'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_stages',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['academic_stages.id'], name=op.f('fk_academic_stages_parent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_stages_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_stages')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_academic_stages_tenant_code')
    )
    op.create_index(op.f('ix_academic_stages_tenant_id'), 'academic_stages', ['tenant_id'], unique=False)
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_years_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_academic_years_tenant_code')
    )
    op.create_index(op.f('ix_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False)
    op.create_table('grading_scales',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('percentage', 'letter', 'gpa', 'descriptor', 'points', name='grading_scale_kind'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_grading_scales_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_scales')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_grading_scales_tenant_code')
    )
    op.create_index(op.f('ix_grading_scales_tenant_id'), 'grading_scales', ['tenant_id'], unique=False)
    op.create_table('terminology_sets',
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='config_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['terminology_sets.id'], name=op.f('fk_terminology_sets_parent_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_terminology_sets_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminology_sets')),
    sa.UniqueConstraint('tenant_id', 'locale', 'version', name='uq_terminology_tenant_locale_version')
    )
    op.create_index(op.f('ix_terminology_sets_tenant_id'), 'terminology_sets', ['tenant_id'], unique=False)
    op.create_table('grading_bands',
    sa.Column('scale_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scale_id'], ['grading_scales.id'], name=op.f('fk_grading_bands_scale_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_grading_bands_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_bands'))
    )
    op.create_index(op.f('ix_grading_bands_tenant_id'), 'grading_bands', ['tenant_id'], unique=False)
    op.create_table('levels',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('next_level_id', sa.UUID(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['next_level_id'], ['levels.id'], name=op.f('fk_levels_next_level_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['academic_stages.id'], name=op.f('fk_levels_stage_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_levels_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_levels_tenant_code')
    )
    op.create_index(op.f('ix_levels_tenant_id'), 'levels', ['tenant_id'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('grading_scale_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['grading_scales.id'], name=op.f('fk_subjects_grading_scale_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subjects_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_subjects_tenant_code')
    )
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.create_table('terms',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_terms_academic_year_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_terms_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms')),
    sa.UniqueConstraint('tenant_id', 'academic_year_id', 'sequence', name='uq_terms_year_seq')
    )
    op.create_index(op.f('ix_terms_tenant_id'), 'terms', ['tenant_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_class_groups_academic_year_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_class_groups_level_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_class_groups_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_groups')),
    sa.UniqueConstraint('tenant_id', 'academic_year_id', 'code', name='uq_class_groups_year_code')
    )
    op.create_index(op.f('ix_class_groups_tenant_id'), 'class_groups', ['tenant_id'], unique=False)
    op.create_table('progression_rules',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('on_pass', sa.Enum('promote', 'repeat', 'review', 'graduate', name='progression_outcome'), nullable=False),
    sa.Column('on_fail', sa.Enum('promote', 'repeat', 'review', 'graduate', name='progression_outcome'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_progression_rules_level_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_progression_rules_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_rules')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_progression_rules_tenant_code')
    )
    op.create_index(op.f('ix_progression_rules_tenant_id'), 'progression_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


    _protect()

def _protect() -> None:
    """Apply and verify row-level security on the tables this migration adds.

    Every migration that creates a tenant-owned table must do this. A new table
    without a policy is a silent hole, and the only reliable way to prevent one
    is to make protection part of the same change that creates it.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            f"Refusing to complete: unprotected tenant-owned tables: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progression_rules_tenant_id'), table_name='progression_rules')
    op.drop_table('progression_rules')
    op.drop_index(op.f('ix_class_groups_tenant_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_terms_tenant_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_levels_tenant_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_grading_bands_tenant_id'), table_name='grading_bands')
    op.drop_table('grading_bands')
    op.drop_index(op.f('ix_terminology_sets_tenant_id'), table_name='terminology_sets')
    op.drop_table('terminology_sets')
    op.drop_index(op.f('ix_grading_scales_tenant_id'), table_name='grading_scales')
    op.drop_table('grading_scales')
    op.drop_index(op.f('ix_academic_years_tenant_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_academic_stages_tenant_id'), table_name='academic_stages')
    op.drop_table('academic_stages')
    # ### end Alembic commands ###
    for type_name in ("grading_scale_kind", "progression_outcome", "config_status"):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
