"""Bulk import: batches and rows.

An import is a change to a school's records, so the record of the import is
part of the record. `import_batches` holds one row per upload — its file, its
mapping, its options and its outcome — and `import_rows` holds every line of
the file with what became of it, which is what makes the error report per-row
and a reversal possible at all.

Both are tenant-owned, so both get row-level security and tenant-scoped foreign
keys from the mechanisms that apply to every such table.

Revision ID: 924989b90e55
Revises: acea85e26e65
Create Date: 2026-08-10 21:54:28.266673
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = '924989b90e55'
down_revision: str | None = 'acea85e26e65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'failed', 'applied', 'reversed', name='import_batch_status'), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('applied_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_batches_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_import_batches_tenant_id_id')
    )
    op.create_index('ix_import_batches_tenant_created', 'import_batches', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'valid', 'invalid', 'duplicate', 'skipped', 'applied', 'reversed', name='import_row_status'), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_by', sa.String(length=120), nullable=True),
    sa.Column('created', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'batch_id'], ['import_batches.tenant_id', 'import_batches.id'], name='fk_import_rows_batch_id_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_rows_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_import_rows_tenant_id_id')
    )
    op.create_index('ix_import_rows_tenant_batch', 'import_rows', ['tenant_id', 'batch_id', 'line_number'], unique=False)
    op.create_index(op.f('ix_import_rows_tenant_id'), 'import_rows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    _protect()


ENUM_TYPES = ("import_batch_status", "import_row_status")


def _protect() -> None:
    """Apply and verify row-level security, and re-issue the role grants."""
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_rows_tenant_id'), table_name='import_rows')
    op.drop_index('ix_import_rows_tenant_batch', table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_index('ix_import_batches_tenant_created', table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
