"""Interface profiles and user preferences.

Almost everything the interface needs is derived — from the rows an institution
has created, the permissions a person holds, and what the plan includes. These
two tables cover what derivation cannot: an institution that has not created
anything yet but knows what it is, and a person's own choices about how they
like to work.

Neither carries an institution *type*. There is no `NURSERY | SECONDARY |
UNIVERSITY` column and there will not be one; that is ADR-024's forbidden enum
arriving through the back door.

Revision ID: 9c48a2f93f57
Revises: bf767662e86c
Create Date: 2026-08-10 22:50:38.649202
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = '9c48a2f93f57'
down_revision: str | None = 'bf767662e86c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_profiles',
    sa.Column('declared_layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suppressed_layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('self_description', sa.String(length=120), nullable=True),
    sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_interface_profiles_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interface_profiles')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_interface_profiles_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', name='uq_interface_profiles_tenant')
    )
    op.create_index(op.f('ix_interface_profiles_tenant_id'), 'interface_profiles', ['tenant_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('colour_scheme', sa.String(length=16), nullable=False),
    sa.Column('density', sa.String(length=16), nullable=False),
    sa.Column('reduce_motion', sa.Boolean(), nullable=False),
    sa.Column('pinned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_preferences_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_user_preferences_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'membership_id', name='uq_user_preferences_member')
    )
    op.create_index(op.f('ix_user_preferences_tenant_id'), 'user_preferences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    _protect()


def _protect() -> None:
    """Apply and verify row-level security, and re-issue the role grants."""
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_tenant_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_interface_profiles_tenant_id'), table_name='interface_profiles')
    op.drop_table('interface_profiles')
    # ### end Alembic commands ###
