"""People, enrolment history, and tenant-scoped foreign keys.

Two changes, and the second is a security fix that applies to the whole schema.

**People.** A `Person` distinct from the `User` who signs in, three relationship
tables so one person may be a learner, a member of staff and somebody's guardian
at once, and an `enrolments` table where placement is a row with a beginning and
an end rather than a mutable pointer. `enrolment_events` loses UPDATE and DELETE
from the application role, joining the audit log as an append-only record;
`enrolments` loses DELETE, because a placement that happened cannot be made not
to have happened.

**Tenant-scoped foreign keys.** Row-level security governs reads and writes but
*not* referential integrity: PostgreSQL performs a foreign-key check without
applying the referenced table's policies. Until this revision, one institution
could insert a row referencing another institution's row — which corrupted the
record, allowed a cross-tenant denial of service through `ON DELETE RESTRICT`,
and, worst, turned every foreign key into an existence oracle for other tenants'
ids. Every foreign key between two tenant-owned tables now references
`(tenant_id, id)`, so a cross-tenant reference has no matching parent row. See
`app.db.tenant_fk` and ADR-026.

`ON DELETE SET NULL` becomes `SET NULL (column)` so that the referencing column
is cleared without also nulling `tenant_id`, which is `NOT NULL`. That form
requires PostgreSQL 15 or later.

Revision ID: acea85e26e65
Revises: edc3f56c06d9
Create Date: 2026-08-10 21:32:52.390171
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.rls import apply_rls, grant_app_role, verify_rls
revision: str = 'acea85e26e65'
down_revision: str | None = 'edc3f56c06d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The pair every tenant-scoped foreign key points at, added before any
    # table that references it: a composite key needs its target unique
    # constraint to exist first, and the new tables below reference these.
    op.create_unique_constraint('uq_academic_periods_tenant_id_id', 'academic_periods', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_academic_stages_tenant_id_id', 'academic_stages', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_academic_units_tenant_id_id', 'academic_units', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_academic_years_tenant_id_id', 'academic_years', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_audit_events_tenant_id_id', 'audit_events', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_class_groups_tenant_id_id', 'class_groups', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_cohorts_tenant_id_id', 'cohorts', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_courses_tenant_id_id', 'courses', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_credit_systems_tenant_id_id', 'credit_systems', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_grading_bands_tenant_id_id', 'grading_bands', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_grading_scales_tenant_id_id', 'grading_scales', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_levels_tenant_id_id', 'levels', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_membership_roles_tenant_id_id', 'membership_roles', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_memberships_tenant_id_id', 'memberships', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_milestone_definitions_tenant_id_id', 'milestone_definitions', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_programmes_tenant_id_id', 'programmes', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_progression_rules_tenant_id_id', 'progression_rules', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_qualifications_tenant_id_id', 'qualifications', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_role_permissions_tenant_id_id', 'role_permissions', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_roles_tenant_id_id', 'roles', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_supervision_roles_tenant_id_id', 'supervision_roles', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_terminology_sets_tenant_id_id', 'terminology_sets', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_user_sessions_tenant_id_id', 'user_sessions', ['tenant_id', 'id'])

    op.create_table('people',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('given_names', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('preferred_name', sa.String(length=120), nullable=True),
    sa.Column('sort_name', sa.String(length=200), nullable=True),
    sa.Column('gender_label', sa.String(length=60), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_people_tenant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_people_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_people_tenant_id_id')
    )
    op.create_index(op.f('ix_people_tenant_id'), 'people', ['tenant_id'], unique=False)
    op.create_index('ix_people_tenant_sort_name', 'people', ['tenant_id', 'sort_name'], unique=False)
    op.create_index('uq_people_tenant_user', 'people', ['tenant_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('guardian_relationships',
    sa.Column('guardian_person_id', sa.UUID(), nullable=False),
    sa.Column('student_person_id', sa.UUID(), nullable=False),
    sa.Column('relationship_label', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.Column('receives_reports', sa.Boolean(), nullable=False),
    sa.Column('may_collect', sa.Boolean(), nullable=False),
    sa.Column('is_financially_responsible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('prospective', 'active', 'suspended', 'ended', name='relationship_status'), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('guardian_person_id <> student_person_id', name=op.f('ck_guardian_relationships_guardian_is_not_the_student')),
    sa.ForeignKeyConstraint(['tenant_id', 'guardian_person_id'], ['people.tenant_id', 'people.id'], name='fk_guardian_relationships_guardian_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_person_id'], ['people.tenant_id', 'people.id'], name='fk_guardian_relationships_student_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_guardian_relationships_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian_relationships')),
    sa.UniqueConstraint('tenant_id', 'guardian_person_id', 'student_person_id', name='uq_guardian_relationships_pair'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_guardian_relationships_tenant_id_id')
    )
    op.create_index(op.f('ix_guardian_relationships_tenant_id'), 'guardian_relationships', ['tenant_id'], unique=False)
    op.create_index('ix_guardian_relationships_tenant_student', 'guardian_relationships', ['tenant_id', 'student_person_id'], unique=False)
    op.create_table('staff_relationships',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('academic_unit_id', sa.UUID(), nullable=True),
    sa.Column('is_teaching', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('prospective', 'active', 'suspended', 'ended', name='relationship_status'), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_unit_id'], ['academic_units.tenant_id', 'academic_units.id'], name='fk_staff_relationships_academic_unit_id_tenant', ondelete='SET NULL (academic_unit_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['people.tenant_id', 'people.id'], name='fk_staff_relationships_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_staff_relationships_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_relationships')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_staff_relationships_tenant_id_id')
    )
    op.create_index(op.f('ix_staff_relationships_tenant_id'), 'staff_relationships', ['tenant_id'], unique=False)
    op.create_index('ix_staff_relationships_tenant_person', 'staff_relationships', ['tenant_id', 'person_id'], unique=False)
    op.create_index('uq_staff_relationships_tenant_reference', 'staff_relationships', ['tenant_id', 'reference'], unique=True, postgresql_where=sa.text('reference IS NOT NULL'))
    op.create_table('student_relationships',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('prospective', 'active', 'suspended', 'ended', name='relationship_status'), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['people.tenant_id', 'people.id'], name='fk_student_relationships_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_student_relationships_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_relationships')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_student_relationships_tenant_id_id')
    )
    op.create_index(op.f('ix_student_relationships_tenant_id'), 'student_relationships', ['tenant_id'], unique=False)
    op.create_index('ix_student_relationships_tenant_person', 'student_relationships', ['tenant_id', 'person_id'], unique=False)
    op.create_index('uq_student_relationships_tenant_reference', 'student_relationships', ['tenant_id', 'reference'], unique=True, postgresql_where=sa.text('reference IS NOT NULL'))
    op.create_table('enrolments',
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('class_group_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('prospective', 'active', 'suspended', 'ended', name='enrolment_status'), nullable=False),
    sa.Column('outcome', sa.Enum('progressed', 'repeated', 'transferred', 'withdrawn', 'completed', 'discontinued', name='enrolment_outcome'), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('previous_enrolment_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(ended_on IS NULL) = (outcome IS NULL)', name=op.f('ck_enrolments_outcome_matches_end')),
    sa.CheckConstraint('ended_on IS NULL OR ended_on >= started_on', name=op.f('ck_enrolments_ends_after_start')),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_year_id'], ['academic_years.tenant_id', 'academic_years.id'], name='fk_enrolments_academic_year_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'class_group_id'], ['class_groups.tenant_id', 'class_groups.id'], name='fk_enrolments_class_group_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'cohort_id'], ['cohorts.tenant_id', 'cohorts.id'], name='fk_enrolments_cohort_id_tenant', ondelete='SET NULL (cohort_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'level_id'], ['levels.tenant_id', 'levels.id'], name='fk_enrolments_level_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'previous_enrolment_id'], ['enrolments.tenant_id', 'enrolments.id'], name='fk_enrolments_previous_enrolment_id_tenant', ondelete='SET NULL (previous_enrolment_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'programme_id'], ['programmes.tenant_id', 'programmes.id'], name='fk_enrolments_programme_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_enrolments_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_enrolments_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrolments')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_enrolments_tenant_id_id')
    )
    op.create_index('ix_enrolments_tenant_class_group', 'enrolments', ['tenant_id', 'class_group_id'], unique=False)
    op.create_index(op.f('ix_enrolments_tenant_id'), 'enrolments', ['tenant_id'], unique=False)
    op.create_index('ix_enrolments_tenant_programme', 'enrolments', ['tenant_id', 'programme_id'], unique=False)
    op.create_index('ix_enrolments_tenant_student', 'enrolments', ['tenant_id', 'student_relationship_id', 'started_on'], unique=False)
    op.create_table('enrolment_events',
    sa.Column('enrolment_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('admitted', 'enrolled', 'placed', 'transferred', 'suspended', 'resumed', 'withdrawn', 'readmitted', 'progressed', 'repeated', 'completed', 'awarded', 'corrected', name='enrolment_event_kind'), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'enrolment_id'], ['enrolments.tenant_id', 'enrolments.id'], name='fk_enrolment_events_enrolment_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_enrolment_events_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrolment_events')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_enrolment_events_tenant_id_id')
    )
    op.create_index('ix_enrolment_events_tenant_enrolment', 'enrolment_events', ['tenant_id', 'enrolment_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_enrolment_events_tenant_id'), 'enrolment_events', ['tenant_id'], unique=False)
    op.create_table('qualification_awards',
    sa.Column('student_relationship_id', sa.UUID(), nullable=False),
    sa.Column('qualification_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('enrolment_id', sa.UUID(), nullable=True),
    sa.Column('awarded_on', sa.Date(), nullable=False),
    sa.Column('classification_label', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('awarded_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'enrolment_id'], ['enrolments.tenant_id', 'enrolments.id'], name='fk_qualification_awards_enrolment_id_tenant', ondelete='SET NULL (enrolment_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'programme_id'], ['programmes.tenant_id', 'programmes.id'], name='fk_qualification_awards_programme_id_tenant', ondelete='SET NULL (programme_id)'),
    sa.ForeignKeyConstraint(['tenant_id', 'qualification_id'], ['qualifications.tenant_id', 'qualifications.id'], name='fk_qualification_awards_qualification_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'student_relationship_id'], ['student_relationships.tenant_id', 'student_relationships.id'], name='fk_qualification_awards_student_relationship_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_qualification_awards_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualification_awards')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_qualification_awards_tenant_id_id')
    )
    op.create_index(op.f('ix_qualification_awards_tenant_id'), 'qualification_awards', ['tenant_id'], unique=False)
    op.create_index('ix_qualification_awards_tenant_student', 'qualification_awards', ['tenant_id', 'student_relationship_id'], unique=False)
    op.create_index('uq_qualification_awards_tenant_reference', 'qualification_awards', ['tenant_id', 'reference'], unique=True, postgresql_where=sa.text('reference IS NOT NULL'))
    op.drop_constraint(op.f('fk_academic_periods_academic_year_id'), 'academic_periods', type_='foreignkey')
    op.create_foreign_key('fk_academic_periods_academic_year_id_tenant', 'academic_periods', 'academic_years', ['tenant_id', 'academic_year_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_academic_stages_parent_id'), 'academic_stages', type_='foreignkey')
    op.create_foreign_key('fk_academic_stages_parent_id_tenant', 'academic_stages', 'academic_stages', ['tenant_id', 'parent_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_academic_units_parent_id'), 'academic_units', type_='foreignkey')
    op.create_foreign_key('fk_academic_units_parent_id_tenant', 'academic_units', 'academic_units', ['tenant_id', 'parent_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_class_groups_academic_year_id'), 'class_groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_class_groups_cohort_id'), 'class_groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_class_groups_level_id'), 'class_groups', type_='foreignkey')
    op.create_foreign_key('fk_class_groups_level_id_tenant', 'class_groups', 'levels', ['tenant_id', 'level_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_class_groups_cohort_id_tenant', 'class_groups', 'cohorts', ['tenant_id', 'cohort_id'], ['tenant_id', 'id'], ondelete='SET NULL (cohort_id)')
    op.create_foreign_key('fk_class_groups_academic_year_id_tenant', 'class_groups', 'academic_years', ['tenant_id', 'academic_year_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_cohorts_academic_year_id'), 'cohorts', type_='foreignkey')
    op.drop_constraint(op.f('fk_cohorts_programme_id'), 'cohorts', type_='foreignkey')
    op.create_foreign_key('fk_cohorts_academic_year_id_tenant', 'cohorts', 'academic_years', ['tenant_id', 'academic_year_id'], ['tenant_id', 'id'], ondelete='SET NULL (academic_year_id)')
    op.create_foreign_key('fk_cohorts_programme_id_tenant', 'cohorts', 'programmes', ['tenant_id', 'programme_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_courses_level_id'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_programme_id'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_credit_system_id'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_grading_scale_id'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_academic_unit_id'), 'courses', type_='foreignkey')
    op.create_foreign_key('fk_courses_grading_scale_id_tenant', 'courses', 'grading_scales', ['tenant_id', 'grading_scale_id'], ['tenant_id', 'id'], ondelete='SET NULL (grading_scale_id)')
    op.create_foreign_key('fk_courses_level_id_tenant', 'courses', 'levels', ['tenant_id', 'level_id'], ['tenant_id', 'id'], ondelete='SET NULL (level_id)')
    op.create_foreign_key('fk_courses_academic_unit_id_tenant', 'courses', 'academic_units', ['tenant_id', 'academic_unit_id'], ['tenant_id', 'id'], ondelete='SET NULL (academic_unit_id)')
    op.create_foreign_key('fk_courses_credit_system_id_tenant', 'courses', 'credit_systems', ['tenant_id', 'credit_system_id'], ['tenant_id', 'id'], ondelete='SET NULL (credit_system_id)')
    op.create_foreign_key('fk_courses_programme_id_tenant', 'courses', 'programmes', ['tenant_id', 'programme_id'], ['tenant_id', 'id'], ondelete='SET NULL (programme_id)')
    op.drop_constraint(op.f('fk_grading_bands_scale_id'), 'grading_bands', type_='foreignkey')
    op.create_foreign_key('fk_grading_bands_scale_id_tenant', 'grading_bands', 'grading_scales', ['tenant_id', 'scale_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_levels_next_level_id'), 'levels', type_='foreignkey')
    op.drop_constraint(op.f('fk_levels_stage_id'), 'levels', type_='foreignkey')
    op.drop_constraint(op.f('fk_levels_programme_id'), 'levels', type_='foreignkey')
    op.create_foreign_key('fk_levels_stage_id_tenant', 'levels', 'academic_stages', ['tenant_id', 'stage_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_levels_programme_id_tenant', 'levels', 'programmes', ['tenant_id', 'programme_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.create_foreign_key('fk_levels_next_level_id_tenant', 'levels', 'levels', ['tenant_id', 'next_level_id'], ['tenant_id', 'id'], ondelete='SET NULL (next_level_id)')
    op.drop_constraint(op.f('fk_membership_roles_membership_id'), 'membership_roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_membership_roles_role_id'), 'membership_roles', type_='foreignkey')
    op.create_foreign_key('fk_membership_roles_role_id_tenant', 'membership_roles', 'roles', ['tenant_id', 'role_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_membership_roles_membership_id_tenant', 'membership_roles', 'memberships', ['tenant_id', 'membership_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_milestone_definitions_programme_id'), 'milestone_definitions', type_='foreignkey')
    op.create_foreign_key('fk_milestone_definitions_programme_id_tenant', 'milestone_definitions', 'programmes', ['tenant_id', 'programme_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_programmes_credit_system_id'), 'programmes', type_='foreignkey')
    op.drop_constraint(op.f('fk_programmes_qualification_id'), 'programmes', type_='foreignkey')
    op.drop_constraint(op.f('fk_programmes_stage_id'), 'programmes', type_='foreignkey')
    op.drop_constraint(op.f('fk_programmes_academic_unit_id'), 'programmes', type_='foreignkey')
    op.create_foreign_key('fk_programmes_stage_id_tenant', 'programmes', 'academic_stages', ['tenant_id', 'stage_id'], ['tenant_id', 'id'], ondelete='SET NULL (stage_id)')
    op.create_foreign_key('fk_programmes_qualification_id_tenant', 'programmes', 'qualifications', ['tenant_id', 'qualification_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_programmes_credit_system_id_tenant', 'programmes', 'credit_systems', ['tenant_id', 'credit_system_id'], ['tenant_id', 'id'], ondelete='SET NULL (credit_system_id)')
    op.create_foreign_key('fk_programmes_academic_unit_id_tenant', 'programmes', 'academic_units', ['tenant_id', 'academic_unit_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_progression_rules_level_id'), 'progression_rules', type_='foreignkey')
    op.create_foreign_key('fk_progression_rules_level_id_tenant', 'progression_rules', 'levels', ['tenant_id', 'level_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_qualifications_credit_system_id'), 'qualifications', type_='foreignkey')
    op.create_foreign_key('fk_qualifications_credit_system_id_tenant', 'qualifications', 'credit_systems', ['tenant_id', 'credit_system_id'], ['tenant_id', 'id'], ondelete='SET NULL (credit_system_id)')
    op.drop_constraint(op.f('fk_role_permissions_role_id'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key('fk_role_permissions_role_id_tenant', 'role_permissions', 'roles', ['tenant_id', 'role_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_terminology_sets_parent_version_id'), 'terminology_sets', type_='foreignkey')
    op.create_foreign_key('fk_terminology_sets_parent_version_id_tenant', 'terminology_sets', 'terminology_sets', ['tenant_id', 'parent_version_id'], ['tenant_id', 'id'], ondelete='SET NULL (parent_version_id)')
    op.drop_constraint(op.f('fk_user_sessions_membership_id'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key('fk_user_sessions_membership_id_tenant', 'user_sessions', 'memberships', ['tenant_id', 'membership_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    _protect()


ENUM_TYPES = (
    "enrolment_event_kind",
    "enrolment_outcome",
    "enrolment_status",
    "relationship_status",
)


def _protect() -> None:
    """Apply and verify row-level security, and re-issue the role grants.

    Re-issuing matters: `GRANT ... ON ALL TABLES` covers the tables that existed
    when it ran and no others, so the tables created here would otherwise be
    unreachable by the application role — and, worse, `enrolment_events` would
    be reachable with exactly the UPDATE and DELETE this revision withholds.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_sessions_membership_id_tenant', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_sessions_membership_id'), 'user_sessions', 'memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_terminology_sets_parent_version_id_tenant', 'terminology_sets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_terminology_sets_parent_version_id'), 'terminology_sets', 'terminology_sets', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_role_permissions_role_id_tenant', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_role_id'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_qualifications_credit_system_id_tenant', 'qualifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_qualifications_credit_system_id'), 'qualifications', 'credit_systems', ['credit_system_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_progression_rules_level_id_tenant', 'progression_rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_progression_rules_level_id'), 'progression_rules', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_programmes_academic_unit_id_tenant', 'programmes', type_='foreignkey')
    op.drop_constraint('fk_programmes_credit_system_id_tenant', 'programmes', type_='foreignkey')
    op.drop_constraint('fk_programmes_qualification_id_tenant', 'programmes', type_='foreignkey')
    op.drop_constraint('fk_programmes_stage_id_tenant', 'programmes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_programmes_academic_unit_id'), 'programmes', 'academic_units', ['academic_unit_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_programmes_stage_id'), 'programmes', 'academic_stages', ['stage_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_programmes_qualification_id'), 'programmes', 'qualifications', ['qualification_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_programmes_credit_system_id'), 'programmes', 'credit_systems', ['credit_system_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_milestone_definitions_programme_id_tenant', 'milestone_definitions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_milestone_definitions_programme_id'), 'milestone_definitions', 'programmes', ['programme_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_membership_roles_membership_id_tenant', 'membership_roles', type_='foreignkey')
    op.drop_constraint('fk_membership_roles_role_id_tenant', 'membership_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_membership_roles_role_id'), 'membership_roles', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_membership_roles_membership_id'), 'membership_roles', 'memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_levels_next_level_id_tenant', 'levels', type_='foreignkey')
    op.drop_constraint('fk_levels_programme_id_tenant', 'levels', type_='foreignkey')
    op.drop_constraint('fk_levels_stage_id_tenant', 'levels', type_='foreignkey')
    op.create_foreign_key(op.f('fk_levels_programme_id'), 'levels', 'programmes', ['programme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_levels_stage_id'), 'levels', 'academic_stages', ['stage_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_levels_next_level_id'), 'levels', 'levels', ['next_level_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_grading_bands_scale_id_tenant', 'grading_bands', type_='foreignkey')
    op.create_foreign_key(op.f('fk_grading_bands_scale_id'), 'grading_bands', 'grading_scales', ['scale_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_courses_programme_id_tenant', 'courses', type_='foreignkey')
    op.drop_constraint('fk_courses_credit_system_id_tenant', 'courses', type_='foreignkey')
    op.drop_constraint('fk_courses_academic_unit_id_tenant', 'courses', type_='foreignkey')
    op.drop_constraint('fk_courses_level_id_tenant', 'courses', type_='foreignkey')
    op.drop_constraint('fk_courses_grading_scale_id_tenant', 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_academic_unit_id'), 'courses', 'academic_units', ['academic_unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_courses_grading_scale_id'), 'courses', 'grading_scales', ['grading_scale_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_courses_credit_system_id'), 'courses', 'credit_systems', ['credit_system_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_courses_programme_id'), 'courses', 'programmes', ['programme_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_courses_level_id'), 'courses', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_cohorts_programme_id_tenant', 'cohorts', type_='foreignkey')
    op.drop_constraint('fk_cohorts_academic_year_id_tenant', 'cohorts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cohorts_programme_id'), 'cohorts', 'programmes', ['programme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_cohorts_academic_year_id'), 'cohorts', 'academic_years', ['academic_year_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_class_groups_academic_year_id_tenant', 'class_groups', type_='foreignkey')
    op.drop_constraint('fk_class_groups_cohort_id_tenant', 'class_groups', type_='foreignkey')
    op.drop_constraint('fk_class_groups_level_id_tenant', 'class_groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_class_groups_level_id'), 'class_groups', 'levels', ['level_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_class_groups_cohort_id'), 'class_groups', 'cohorts', ['cohort_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_class_groups_academic_year_id'), 'class_groups', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_academic_units_parent_id_tenant', 'academic_units', type_='foreignkey')
    op.create_foreign_key(op.f('fk_academic_units_parent_id'), 'academic_units', 'academic_units', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_academic_stages_parent_id_tenant', 'academic_stages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_academic_stages_parent_id'), 'academic_stages', 'academic_stages', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('fk_academic_periods_academic_year_id_tenant', 'academic_periods', type_='foreignkey')
    op.create_foreign_key(op.f('fk_academic_periods_academic_year_id'), 'academic_periods', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_qualification_awards_tenant_reference', table_name='qualification_awards', postgresql_where=sa.text('reference IS NOT NULL'))
    op.drop_index('ix_qualification_awards_tenant_student', table_name='qualification_awards')
    op.drop_index(op.f('ix_qualification_awards_tenant_id'), table_name='qualification_awards')
    op.drop_table('qualification_awards')
    op.drop_index(op.f('ix_enrolment_events_tenant_id'), table_name='enrolment_events')
    op.drop_index('ix_enrolment_events_tenant_enrolment', table_name='enrolment_events')
    op.drop_table('enrolment_events')
    op.drop_index('ix_enrolments_tenant_student', table_name='enrolments')
    op.drop_index('ix_enrolments_tenant_programme', table_name='enrolments')
    op.drop_index(op.f('ix_enrolments_tenant_id'), table_name='enrolments')
    op.drop_index('ix_enrolments_tenant_class_group', table_name='enrolments')
    op.drop_table('enrolments')
    op.drop_index('uq_student_relationships_tenant_reference', table_name='student_relationships', postgresql_where=sa.text('reference IS NOT NULL'))
    op.drop_index('ix_student_relationships_tenant_person', table_name='student_relationships')
    op.drop_index(op.f('ix_student_relationships_tenant_id'), table_name='student_relationships')
    op.drop_table('student_relationships')
    op.drop_index('uq_staff_relationships_tenant_reference', table_name='staff_relationships', postgresql_where=sa.text('reference IS NOT NULL'))
    op.drop_index('ix_staff_relationships_tenant_person', table_name='staff_relationships')
    op.drop_index(op.f('ix_staff_relationships_tenant_id'), table_name='staff_relationships')
    op.drop_table('staff_relationships')
    op.drop_index('ix_guardian_relationships_tenant_student', table_name='guardian_relationships')
    op.drop_index(op.f('ix_guardian_relationships_tenant_id'), table_name='guardian_relationships')
    op.drop_table('guardian_relationships')
    op.drop_index('uq_people_tenant_user', table_name='people', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_people_tenant_sort_name', table_name='people')
    op.drop_index(op.f('ix_people_tenant_id'), table_name='people')
    op.drop_table('people')

    # Last, and for the mirror-image reason: these unique constraints are
    # the target of foreign keys on the tables dropped just above.
    op.drop_constraint('uq_user_sessions_tenant_id_id', 'user_sessions', type_='unique')
    op.drop_constraint('uq_terminology_sets_tenant_id_id', 'terminology_sets', type_='unique')
    op.drop_constraint('uq_supervision_roles_tenant_id_id', 'supervision_roles', type_='unique')
    op.drop_constraint('uq_roles_tenant_id_id', 'roles', type_='unique')
    op.drop_constraint('uq_role_permissions_tenant_id_id', 'role_permissions', type_='unique')
    op.drop_constraint('uq_qualifications_tenant_id_id', 'qualifications', type_='unique')
    op.drop_constraint('uq_progression_rules_tenant_id_id', 'progression_rules', type_='unique')
    op.drop_constraint('uq_programmes_tenant_id_id', 'programmes', type_='unique')
    op.drop_constraint('uq_milestone_definitions_tenant_id_id', 'milestone_definitions', type_='unique')
    op.drop_constraint('uq_memberships_tenant_id_id', 'memberships', type_='unique')
    op.drop_constraint('uq_membership_roles_tenant_id_id', 'membership_roles', type_='unique')
    op.drop_constraint('uq_levels_tenant_id_id', 'levels', type_='unique')
    op.drop_constraint('uq_grading_scales_tenant_id_id', 'grading_scales', type_='unique')
    op.drop_constraint('uq_grading_bands_tenant_id_id', 'grading_bands', type_='unique')
    op.drop_constraint('uq_credit_systems_tenant_id_id', 'credit_systems', type_='unique')
    op.drop_constraint('uq_courses_tenant_id_id', 'courses', type_='unique')
    op.drop_constraint('uq_cohorts_tenant_id_id', 'cohorts', type_='unique')
    op.drop_constraint('uq_class_groups_tenant_id_id', 'class_groups', type_='unique')
    op.drop_constraint('uq_audit_events_tenant_id_id', 'audit_events', type_='unique')
    op.drop_constraint('uq_academic_years_tenant_id_id', 'academic_years', type_='unique')
    op.drop_constraint('uq_academic_units_tenant_id_id', 'academic_units', type_='unique')
    op.drop_constraint('uq_academic_stages_tenant_id_id', 'academic_stages', type_='unique')
    op.drop_constraint('uq_academic_periods_tenant_id_id', 'academic_periods', type_='unique')
    # ### end Alembic commands ###
    # Autogenerate creates enum types with their tables and never drops them,
    # so downgrade-then-upgrade would fail on "type already exists" — exactly
    # what an incident rollback does.
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
