"""signatory registry and seal registry

Revision ID: b61db28c5cc8
Revises: 329c59898206
Create Date: 2026-08-11 12:31:36.921105
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.rls import apply_rls, grant_app_role, verify_rls
revision: str = 'b61db28c5cc8'
down_revision: str | None = '329c59898206'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `drop_table` leaves the enum types behind, and the next `upgrade` then fails
# on types that already exist.
ENUM_TYPES = (
    "signatory_appointment_status",
    "signature_asset_kind",
    "signature_asset_status",
    "seal_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seals',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('drafted', 'approved', 'superseded', 'revoked', name='seal_status'), nullable=False),
    sa.Column('in_force_from', sa.Date(), nullable=False),
    sa.Column('in_force_until', sa.Date(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('approved_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('in_force_until IS NULL OR in_force_until >= in_force_from', name=op.f('ck_seals_in_force_range')),
    sa.ForeignKeyConstraint(['tenant_id', 'superseded_by_id'], ['seals.tenant_id', 'seals.id'], name='fk_seals_superseded_by_id_tenant', ondelete='SET NULL (superseded_by_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_seals_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seals')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_seals_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_seals_tenant_id_id')
    )
    op.create_index(op.f('ix_seals_tenant_id'), 'seals', ['tenant_id'], unique=False)
    op.create_table('signatory_offices',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('printed_title', sa.String(length=200), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_signatory_offices_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatory_offices')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_signatory_offices_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_signatory_offices_tenant_id_id')
    )
    op.create_index(op.f('ix_signatory_offices_tenant_id'), 'signatory_offices', ['tenant_id'], unique=False)
    op.create_index('ix_signatory_offices_tenant_sequence', 'signatory_offices', ['tenant_id', 'sequence'], unique=False)
    op.create_table('signature_assets',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'typeset', name='signature_asset_kind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('drafted', 'approved', 'superseded', 'revoked', name='signature_asset_status'), nullable=False),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('approved_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('revoked_on', sa.Date(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(kind = 'image') = (content IS NOT NULL)", name=op.f('ck_signature_assets_image_has_content')),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['people.tenant_id', 'people.id'], name='fk_signature_assets_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_signature_assets_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_assets')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_signature_assets_tenant_id_id')
    )
    op.create_index(op.f('ix_signature_assets_tenant_id'), 'signature_assets', ['tenant_id'], unique=False)
    op.create_index('ix_signature_assets_tenant_person', 'signature_assets', ['tenant_id', 'person_id'], unique=False)
    op.create_table('signatory_appointments',
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('staff_relationship_id', sa.UUID(), nullable=True),
    sa.Column('signature_asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'revoked', 'ended', name='signatory_appointment_status'), nullable=False),
    sa.Column('appointed_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('ended_reason', sa.String(length=200), nullable=True),
    sa.Column('purposes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('printed_name', sa.String(length=200), nullable=True),
    sa.Column('printed_title', sa.String(length=200), nullable=True),
    sa.Column('authorised_at', sa.Date(), nullable=True),
    sa.Column('authorised_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('ended_on IS NULL OR ended_on >= appointed_on', name=op.f('ck_signatory_appointments_ends_after_appointment')),
    sa.ForeignKeyConstraint(['tenant_id', 'office_id'], ['signatory_offices.tenant_id', 'signatory_offices.id'], name='fk_signatory_appointments_office_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['people.tenant_id', 'people.id'], name='fk_signatory_appointments_person_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'signature_asset_id'], ['signature_assets.tenant_id', 'signature_assets.id'], name='fk_signatory_appointments_signature_asset_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'staff_relationship_id'], ['staff_relationships.tenant_id', 'staff_relationships.id'], name='fk_signatory_appointments_staff_relationship_id_tenant', ondelete='SET NULL (staff_relationship_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_signatory_appointments_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatory_appointments')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_signatory_appointments_tenant_id_id')
    )
    op.create_index(op.f('ix_signatory_appointments_tenant_id'), 'signatory_appointments', ['tenant_id'], unique=False)
    op.create_index('ix_signatory_appointments_tenant_office', 'signatory_appointments', ['tenant_id', 'office_id', 'appointed_on'], unique=False)
    op.create_index('uq_signatory_appointments_live', 'signatory_appointments', ['tenant_id', 'office_id'], unique=True, postgresql_where=sa.text("ended_on IS NULL AND status <> 'ended'"))
    op.add_column('documents', sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('documents', sa.Column('seal_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('seal_digest', sa.String(length=64), nullable=True))
    op.create_foreign_key('fk_documents_seal_id_tenant', 'documents', 'seals', ['tenant_id', 'seal_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
    _protect()


def _protect() -> None:
    """Four new tenant-owned tables get their policy before anything is written.

    Authority records in particular: an institution's list of who may sign its
    degrees is not a table to leave one deploy without isolation.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_seal_id_tenant', 'documents', type_='foreignkey')
    op.drop_column('documents', 'seal_digest')
    op.drop_column('documents', 'seal_id')
    op.drop_column('documents', 'signatures')
    op.drop_index('uq_signatory_appointments_live', table_name='signatory_appointments', postgresql_where=sa.text("ended_on IS NULL AND status <> 'ended'"))
    op.drop_index('ix_signatory_appointments_tenant_office', table_name='signatory_appointments')
    op.drop_index(op.f('ix_signatory_appointments_tenant_id'), table_name='signatory_appointments')
    op.drop_table('signatory_appointments')
    op.drop_index('ix_signature_assets_tenant_person', table_name='signature_assets')
    op.drop_index(op.f('ix_signature_assets_tenant_id'), table_name='signature_assets')
    op.drop_table('signature_assets')
    op.drop_index('ix_signatory_offices_tenant_sequence', table_name='signatory_offices')
    op.drop_index(op.f('ix_signatory_offices_tenant_id'), table_name='signatory_offices')
    op.drop_table('signatory_offices')
    op.drop_index(op.f('ix_seals_tenant_id'), table_name='seals')
    op.drop_table('seals')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
