"""Plans, subscriptions, entitlements, institution settings, and usage.

Seven tables and four different questions. `plans`, `plan_features` and
`plan_limits` are **platform** rows and deliberately not tenant-owned: a plan is
EdirasX's product, and a school able to write to its own plan would be editing
its own bill. The rest are tenant-owned and get row-level security and
tenant-scoped foreign keys from the usual mechanisms.

`feature_settings` is the table most billing systems never build: what the
institution has switched off *for itself*, which is a different fact from not
having bought it and produces a different sentence for a different person.

Revision ID: bf767662e86c
Revises: e09e2faf9384
Create Date: 2026-08-10 22:37:23.126353
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = 'bf767662e86c'
down_revision: str | None = 'e09e2faf9384'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_key'), 'plans', ['key'], unique=True)
    op.create_table('feature_settings',
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('changed_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_feature_settings_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_settings')),
    sa.UniqueConstraint('tenant_id', 'feature_key', name='uq_feature_settings_key'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_feature_settings_tenant_id_id')
    )
    op.create_index(op.f('ix_feature_settings_tenant_id'), 'feature_settings', ['tenant_id'], unique=False)
    op.create_table('plan_features',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_features_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_features')),
    sa.UniqueConstraint('plan_id', 'feature_key', name='uq_plan_features_plan_key')
    )
    op.create_table('plan_limits',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('limit_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_limits_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_limits')),
    sa.UniqueConstraint('plan_id', 'limit_key', name='uq_plan_limits_plan_key')
    )
    op.create_table('subscription_overrides',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscription_overrides_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_overrides')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_subscription_overrides_tenant_id_id')
    )
    op.create_index(op.f('ix_subscription_overrides_tenant_id'), 'subscription_overrides', ['tenant_id'], unique=False)
    op.create_index('ix_subscription_overrides_tenant_key', 'subscription_overrides', ['tenant_id', 'key'], unique=False)
    op.create_table('subscriptions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'paused', 'canceled', name='subscription_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_subscriptions_tenant_id_id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index('ix_subscriptions_tenant_status', 'subscriptions', ['tenant_id', 'status'], unique=False)
    op.create_table('usage_records',
    sa.Column('meter_key', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('feature_key', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_usage_records_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_usage_records_tenant_id_id')
    )
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_index('ix_usage_records_tenant_meter_period', 'usage_records', ['tenant_id', 'meter_key', 'period_start'], unique=False)
    # ### end Alembic commands ###
    _protect()


ENUM_TYPES = ("subscription_status",)


def _protect() -> None:
    """Apply and verify row-level security, and re-issue the role grants."""
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_tenant_meter_period', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_subscriptions_tenant_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_subscription_overrides_tenant_key', table_name='subscription_overrides')
    op.drop_index(op.f('ix_subscription_overrides_tenant_id'), table_name='subscription_overrides')
    op.drop_table('subscription_overrides')
    op.drop_table('plan_limits')
    op.drop_table('plan_features')
    op.drop_index(op.f('ix_feature_settings_tenant_id'), table_name='feature_settings')
    op.drop_table('feature_settings')
    op.drop_index(op.f('ix_plans_key'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
