"""sign issued documents

Revision ID: d0250724ba40
Revises: 300c3632c3b0
Create Date: 2026-08-11 09:09:09.766778
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls

revision: str = 'd0250724ba40'
down_revision: str | None = '300c3632c3b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash_key_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    _protect()


def _protect() -> None:
    """Re-apply row-level security and re-issue the grants.

    Nothing structural changes here, but the grants are re-issued on every
    revision so a new column never arrives on a table whose DELETE was revoked
    and quietly restores it.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'hash_key_version')
    # ### end Alembic commands ###
