"""Teaching allocations, and the security event for elevated system access.

`teaching_allocations` is what makes the `taught_by_self` scope answerable in
SQL: which class groups this membership currently teaches. Keyed on membership
rather than on a staff record because it exists to answer an authorization
question, and authorization is built on the membership throughout — a teacher
with no login teaches nobody as far as request handling is concerned.

The enum gains `system_access`, recorded whenever a background job or system
operation reads without a scope — inside one tenant, with a stated reason
(`authz.predicates.system_access`).

Revision ID: e09e2faf9384
Revises: 924989b90e55
Create Date: 2026-08-10 22:20:04.743025
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls

revision: str = 'e09e2faf9384'
down_revision: str | None = '924989b90e55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_allocations',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'academic_year_id'], ['academic_years.tenant_id', 'academic_years.id'], name='fk_teaching_allocations_academic_year_id_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'class_group_id'], ['class_groups.tenant_id', 'class_groups.id'], name='fk_teaching_allocations_class_group_id_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'course_id'], ['courses.tenant_id', 'courses.id'], name='fk_teaching_allocations_course_id_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['memberships.tenant_id', 'memberships.id'], name='fk_teaching_allocations_membership_id_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_teaching_allocations_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_allocations')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_teaching_allocations_tenant_id_id')
    )
    op.create_index('ix_teaching_allocations_tenant_class', 'teaching_allocations', ['tenant_id', 'class_group_id'], unique=False)
    op.create_index(op.f('ix_teaching_allocations_tenant_id'), 'teaching_allocations', ['tenant_id'], unique=False)
    op.create_index('ix_teaching_allocations_tenant_membership', 'teaching_allocations', ['tenant_id', 'membership_id'], unique=False)
    # ### end Alembic commands ###
    # Alembic does not model enum value additions. PostgreSQL adds them in
    # place and cannot remove one, which is why the downgrade does not try: a
    # value nothing writes is inert, and failing a rollback over it would be
    # worse than leaving it.
    op.execute("ALTER TYPE security_event_kind ADD VALUE IF NOT EXISTS 'system_access'")
    _protect()


def _protect() -> None:
    """Apply and verify row-level security, and re-issue the role grants."""
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teaching_allocations_tenant_membership', table_name='teaching_allocations')
    op.drop_index(op.f('ix_teaching_allocations_tenant_id'), table_name='teaching_allocations')
    op.drop_index('ix_teaching_allocations_tenant_class', table_name='teaching_allocations')
    op.drop_table('teaching_allocations')
    # ### end Alembic commands ###
