"""multi-factor authentication fields

Revision ID: e7543f431749
Revises: ea2d6eaf949b
Create Date: 2026-08-10 20:04:55.050348
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'e7543f431749'
down_revision: str | None = 'ea2d6eaf949b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_last_counter', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_recovery_hashes')
    op.drop_column('users', 'mfa_last_counter')
    # ### end Alembic commands ###
