"""Baseline: the universal education schema, with row-level security applied
and verified.

Squashed from three pre-release revisions when the academic model was
generalised from a school-shaped structure to one spanning early years to
doctoral research. There is no production data behind this branch, so a single
honest baseline is better than a rename chain that no deployment will ever
execute — and better than migrations whose drop/create ordering only ever
worked by accident.

The table definitions are autogenerated. The last step is not: row-level
security is applied and then verified, and this migration refuses to complete
if any tenant-owned table is left unprotected.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.rls import apply_rls, grant_app_role, verify_rls
from sqlalchemy.dialects import postgresql
revision: str = 'edc3f56c06d9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('login_failed', 'account_locked', 'tenant_mismatch', 'unknown_host', 'refresh_reuse', 'permission_denied', 'scope_denied', 'rate_limited', 'cross_tenant_write_attempt', 'break_glass', name='security_event_kind'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='security_event_severity'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index('ix_security_events_kind_created', 'security_events', ['kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_security_events_tenant_id'), 'security_events', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('provisioning', 'active', 'suspended', 'archived', name='tenant_status'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', 'deactivated', name='user_status'), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_last_counter', sa.BigInteger(), nullable=True),
    sa.Column('mfa_recovery_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_platform_operator', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('academic_stages',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['academic_stages.id'], name=op.f('fk_academic_stages_parent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_stages_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_stages')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_academic_stages_tenant_code')
    )
    op.create_index(op.f('ix_academic_stages_tenant_id'), 'academic_stages', ['tenant_id'], unique=False)
    op.create_table('academic_units',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('head_membership_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['academic_units.id'], name=op.f('fk_academic_units_parent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_units_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_units')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_academic_units_tenant_code')
    )
    op.create_index(op.f('ix_academic_units_tenant_id'), 'academic_units', ['tenant_id'], unique=False)
    op.create_table('academic_years',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_years_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_academic_years_tenant_code')
    )
    op.create_index(op.f('ix_academic_years_tenant_id'), 'academic_years', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'read_sensitive', 'approve', 'publish', 'unpublish', 'export', 'login', 'logout', 'grant', 'revoke', 'configure', 'rollback', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_tenant_actor', 'audit_events', ['tenant_id', 'actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_events_tenant_resource', 'audit_events', ['tenant_id', 'resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_table('credit_systems',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('unit_label', sa.String(length=60), nullable=False),
    sa.Column('unit_label_plural', sa.String(length=60), nullable=False),
    sa.Column('hours_per_unit', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_credit_systems_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_systems')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_credit_systems_tenant_code')
    )
    op.create_index(op.f('ix_credit_systems_tenant_id'), 'credit_systems', ['tenant_id'], unique=False)
    op.create_table('grading_scales',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('percentage', 'letter', 'gpa', 'descriptor', 'points', name='grading_scale_kind'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_grading_scales_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_scales')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_grading_scales_tenant_code')
    )
    op.create_index(op.f('ix_grading_scales_tenant_id'), 'grading_scales', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', 'ended', name='membership_status'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_memberships_tenant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_memberships_tenant_id_user_id')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_roles_tenant_id_key')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('supervision_roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('max_per_student', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('max_per_student IS NULL OR max_per_student > 0', name=op.f('ck_supervision_roles_ck_supervision_roles_positive_max')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_supervision_roles_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervision_roles')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_supervision_roles_tenant_code')
    )
    op.create_index(op.f('ix_supervision_roles_tenant_id'), 'supervision_roles', ['tenant_id'], unique=False)
    op.create_table('tenant_domains',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('kind', sa.Enum('subdomain', 'custom', name='tenant_domain_kind'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_domains_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_domains')),
    sa.UniqueConstraint('hostname', name='uq_tenant_domains_hostname')
    )
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    op.create_table('terminology_sets',
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='config_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['terminology_sets.id'], name=op.f('fk_terminology_sets_parent_version_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_terminology_sets_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminology_sets')),
    sa.UniqueConstraint('tenant_id', 'locale', 'version', name='uq_terminology_tenant_locale_version')
    )
    op.create_index(op.f('ix_terminology_sets_tenant_id'), 'terminology_sets', ['tenant_id'], unique=False)
    op.create_table('academic_periods',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_academic_periods_academic_year_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_academic_periods_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_periods')),
    sa.UniqueConstraint('tenant_id', 'academic_year_id', 'sequence', name='uq_academic_periods_year_seq')
    )
    op.create_index(op.f('ix_academic_periods_tenant_id'), 'academic_periods', ['tenant_id'], unique=False)
    op.create_table('grading_bands',
    sa.Column('scale_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scale_id'], ['grading_scales.id'], name=op.f('fk_grading_bands_scale_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_grading_bands_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_bands'))
    )
    op.create_index(op.f('ix_grading_bands_tenant_id'), 'grading_bands', ['tenant_id'], unique=False)
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('granted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_membership_roles_membership_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_membership_roles_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_membership_roles_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_roles')),
    sa.UniqueConstraint('tenant_id', 'membership_id', 'role_id', name='uq_membership_roles_membership_role')
    )
    op.create_index(op.f('ix_membership_roles_tenant_id'), 'membership_roles', ['tenant_id'], unique=False)
    op.create_table('qualifications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category_label', sa.String(length=80), nullable=True),
    sa.Column('framework_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('awarding_body', sa.String(length=200), nullable=True),
    sa.Column('typical_duration_periods', sa.Integer(), nullable=True),
    sa.Column('required_credits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_system_id', sa.UUID(), nullable=True),
    sa.Column('completion_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credit_system_id'], ['credit_systems.id'], name=op.f('fk_qualifications_credit_system_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_qualifications_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_qualifications_tenant_code')
    )
    op.create_index(op.f('ix_qualifications_tenant_id'), 'qualifications', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=96), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_role_permissions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('tenant_id', 'role_id', 'permission', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('rotated_from_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_user_sessions_membership_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_sessions_tenant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False)
    op.create_table('programmes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('academic_unit_id', sa.UUID(), nullable=True),
    sa.Column('qualification_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('duration_periods', sa.Integer(), nullable=True),
    sa.Column('required_credits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_system_id', sa.UUID(), nullable=True),
    sa.Column('is_research', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], name=op.f('fk_programmes_academic_unit_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credit_system_id'], ['credit_systems.id'], name=op.f('fk_programmes_credit_system_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('fk_programmes_qualification_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['academic_stages.id'], name=op.f('fk_programmes_stage_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_programmes_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programmes')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_programmes_tenant_code')
    )
    op.create_index(op.f('ix_programmes_tenant_id'), 'programmes', ['tenant_id'], unique=False)
    op.create_table('cohorts',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_cohorts_academic_year_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_cohorts_programme_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_cohorts_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_cohorts_tenant_code')
    )
    op.create_index(op.f('ix_cohorts_tenant_id'), 'cohorts', ['tenant_id'], unique=False)
    op.create_table('levels',
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('next_level_id', sa.UUID(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('stage_id IS NOT NULL OR programme_id IS NOT NULL', name=op.f('ck_levels_ck_levels_belongs_to_something')),
    sa.ForeignKeyConstraint(['next_level_id'], ['levels.id'], name=op.f('fk_levels_next_level_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_levels_programme_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['academic_stages.id'], name=op.f('fk_levels_stage_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_levels_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_levels_tenant_code')
    )
    op.create_index(op.f('ix_levels_tenant_id'), 'levels', ['tenant_id'], unique=False)
    op.create_table('milestone_definitions',
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('expected_offset_months', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('approver_role_key', sa.String(length=64), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_milestone_definitions_programme_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_milestone_definitions_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_definitions')),
    sa.UniqueConstraint('tenant_id', 'programme_id', 'code', name='uq_milestone_prog_code')
    )
    op.create_index(op.f('ix_milestone_definitions_tenant_id'), 'milestone_definitions', ['tenant_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('kind_label', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_class_groups_academic_year_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_class_groups_cohort_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_class_groups_level_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_class_groups_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_groups')),
    sa.UniqueConstraint('tenant_id', 'academic_year_id', 'code', name='uq_class_groups_year_code')
    )
    op.create_index(op.f('ix_class_groups_tenant_id'), 'class_groups', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('credit_system_id', sa.UUID(), nullable=True),
    sa.Column('contact_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('academic_unit_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('grading_scale_id', sa.UUID(), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_unit_id'], ['academic_units.id'], name=op.f('fk_courses_academic_unit_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_system_id'], ['credit_systems.id'], name=op.f('fk_courses_credit_system_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['grading_scales.id'], name=op.f('fk_courses_grading_scale_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_courses_level_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name=op.f('fk_courses_programme_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_courses_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_courses_tenant_code')
    )
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('progression_rules',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('on_pass', sa.Enum('promote', 'repeat', 'review', 'graduate', name='progression_outcome'), nullable=False),
    sa.Column('on_fail', sa.Enum('promote', 'repeat', 'review', 'graduate', name='progression_outcome'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_progression_rules_level_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_progression_rules_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progression_rules')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_progression_rules_tenant_code')
    )
    op.create_index(op.f('ix_progression_rules_tenant_id'), 'progression_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


    _protect()

ENUM_TYPES = ('audit_action', 'config_status', 'grading_scale_kind', 'membership_status', 'progression_outcome', 'security_event_kind', 'security_event_severity', 'tenant_domain_kind', 'tenant_status', 'user_status')


def _protect() -> None:
    """Apply and verify row-level security on every tenant-owned table.

    Uses the same helpers the schema builder and the runbook use, so there is
    exactly one definition of what "protected" means.
    """
    connection = op.get_bind()
    apply_rls(connection)
    grant_app_role(connection, "edtechx_app")
    unprotected = verify_rls(connection)
    if unprotected:
        raise RuntimeError(
            "Refusing to complete: tenant-owned tables without row-level "
            f"security: {sorted(unprotected)}"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progression_rules_tenant_id'), table_name='progression_rules')
    op.drop_table('progression_rules')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_class_groups_tenant_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_milestone_definitions_tenant_id'), table_name='milestone_definitions')
    op.drop_table('milestone_definitions')
    op.drop_index(op.f('ix_levels_tenant_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_cohorts_tenant_id'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_programmes_tenant_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_user_sessions_tenant_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_qualifications_tenant_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_membership_roles_tenant_id'), table_name='membership_roles')
    op.drop_table('membership_roles')
    op.drop_index(op.f('ix_grading_bands_tenant_id'), table_name='grading_bands')
    op.drop_table('grading_bands')
    op.drop_index(op.f('ix_academic_periods_tenant_id'), table_name='academic_periods')
    op.drop_table('academic_periods')
    op.drop_index(op.f('ix_terminology_sets_tenant_id'), table_name='terminology_sets')
    op.drop_table('terminology_sets')
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_supervision_roles_tenant_id'), table_name='supervision_roles')
    op.drop_table('supervision_roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_grading_scales_tenant_id'), table_name='grading_scales')
    op.drop_table('grading_scales')
    op.drop_index(op.f('ix_credit_systems_tenant_id'), table_name='credit_systems')
    op.drop_table('credit_systems')
    op.drop_index('ix_audit_events_tenant_resource', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_actor', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_academic_years_tenant_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_academic_units_tenant_id'), table_name='academic_units')
    op.drop_table('academic_units')
    op.drop_index(op.f('ix_academic_stages_tenant_id'), table_name='academic_stages')
    op.drop_table('academic_stages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_security_events_tenant_id'), table_name='security_events')
    op.drop_index('ix_security_events_kind_created', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
    # Autogenerate creates enum types with their tables and never drops them,
    # so downgrade-then-upgrade would fail on "type already exists" — exactly
    # what an incident rollback does.
    for type_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
