"""add guest, verification, google sso, token version, auth tokens

Revision ID: 1d754ab2dadd
Revises: 5910c8fccaf1
Create Date: 2026-07-30 10:40:02.086868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d754ab2dadd'
down_revision: Union[str, None] = '5910c8fccaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('password_reset', 'email_verify', name='auth_token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    # server_default on the boolean/integer columns below: this table already
    # has rows in any real deployment, and Postgres requires a default (not
    # just the ORM-level Python default, which only applies to inserts made
    # through SQLAlchemy) to backfill a new NOT NULL column against them.
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_users_google_sub', 'users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_google_sub', 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_guest')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
    # Not auto-generated: dropping the table does not drop the ENUM type
    # Postgres created for its 'purpose' column, so a bare downgrade left a
    # stale `auth_token_purpose` type behind that collided with re-upgrading.
    sa.Enum(name='auth_token_purpose').drop(op.get_bind(), checkfirst=True)
