"""add composite indexes for pagination and audit findings

Revision ID: 5910c8fccaf1
Revises: 75afaa9b7250
Create Date: 2026-07-30 06:40:40.078007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5910c8fccaf1'
down_revision: Union[str, None] = '75afaa9b7250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_chapters_book_id'), table_name='book_chapters')
    op.create_index('ix_book_chapters_book_order', 'book_chapters', ['book_id', 'order_index'], unique=False)
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.create_index('ix_books_user_updated', 'books', ['user_id', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_quran_plans_user_id'), table_name='quran_plans')
    op.create_index('ix_quran_plans_user_created', 'quran_plans', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_quran_review_logs_item_id'), table_name='quran_review_logs')
    op.create_index('ix_quran_review_logs_item_created', 'quran_review_logs', ['item_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_quran_revision_items_plan_id'), table_name='quran_revision_items')
    op.create_index('ix_quran_revision_items_plan_due', 'quran_revision_items', ['plan_id', 'due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quran_revision_items_plan_due', table_name='quran_revision_items')
    op.create_index(op.f('ix_quran_revision_items_plan_id'), 'quran_revision_items', ['plan_id'], unique=False)
    op.drop_index('ix_quran_review_logs_item_created', table_name='quran_review_logs')
    op.create_index(op.f('ix_quran_review_logs_item_id'), 'quran_review_logs', ['item_id'], unique=False)
    op.drop_index('ix_quran_plans_user_created', table_name='quran_plans')
    op.create_index(op.f('ix_quran_plans_user_id'), 'quran_plans', ['user_id'], unique=False)
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index('ix_books_user_updated', table_name='books')
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.drop_index('ix_book_chapters_book_order', table_name='book_chapters')
    op.create_index(op.f('ix_book_chapters_book_id'), 'book_chapters', ['book_id'], unique=False)
    # ### end Alembic commands ###
